site_name: MACE

plugins:
  - mkdocstrings
  - search


nav:
  - Home: index.md
  - About: about.md
  - Reference:
    - Size: reference/test.md
    - Name: reference.md
  - License: license.md

theme: material