name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version:  ${{ matrix.python-version }}
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      
      - name : run linting
        run: |
          isort . --diff
          black . --check --diff
          flake8 .

      - name: run tests
        run: |
          pytest

