name: release

on:
  pull_request:
    branches:
      release

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/uv-action@v1
      - run: uv sync
      - run: uv build
    
  pypi:
    runs-on: ubuntu-latest
    needs: sync
    